# Generated by Django 3.2.5 on 2021-07-22 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedAccount',
            fields=[
                ('ver_acc_id', models.AutoField(db_column='VER_ACC_ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_acc_verified', models.BooleanField(blank=True, db_column='VER_ACC_VERIFIED', null=True, verbose_name='VERIFIED')),
                ('id', models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Verified account.',
                'verbose_name_plural': 'Verified accounts.',
                'db_table': 'verified_account',
                'managed': True,
            },
        ),
    ]
